### ISSUE TITLE
Initialized 0 spawners in 0.006 seconds

### ISSUE THREAD

**Issue by saurav-bhagat** [ni/jupyterhub-winlocalprocessspawner#10]
I installed the package and change the class to use this package. But when I'm running the server, I'm getting this message and server stops. I'm not getting any url.

**Comment by adelcast** [comment]
Hi @saurav-bhagat 

I am going to need more information to be able to determine what's going on. Can you run jupyerhub with the --debug and include the output? do you see any errors there?

also please include the version of JupyterHub that you are testing with

**Comment by adelcast** [comment]
not enough info to follow up, closing
