### ISSUE TITLE
Is there a parameter to restrict user acces to some starting folder

### ISSUE THREAD

**Issue by ghost** [ni/jupyterhub-winlocalprocessspawner#13]
As suggested in Jupyterhub documentation:

`jupyterhub --Spawner.notebook_dir='~/assignments'`

Has jupyterhub-winlocalprocessspawner this capacity ?

Thank you!

**Comment by adelcast** [comment]
WinLocalProcessSpawner inherits from LocalProcessSpawner so it should work...did you try it?

**Comment by ghost** [comment]
It did work ! thank you for pointing out !
