### ISSUE TITLE
Wrong value of TEMP env var in the single user server env

### ISSUE THREAD

**Issue by ociule** [ni/jupyterhub-winlocalprocessspawner#6]
Hi there,

I noticed that the  TEMP env var inherits its value from the parent admin user (the one that launches jupyterhub). This breaks many things, like plotly orca.

The cause is in winlocalprocessspawner.py, line 32:

```
    def get_env(self):
        """Get the complete set of environment variables to be set in the spawned process."""
        #win_env_keep = ['SYSTEMROOT', 'APPDATA', 'WINDIR', 'USERPROFILE', 'TEMP']
```

TEMP should not be passed to the spawned process. Instead, it should be copied from the user_env recovered in start(), line 68.

I hope I can put a patch together soon.

I notice very few env vars are copied from that user_env. Is this a normal practice ? Shouldn't the single user spawned process get the full user_env ?

**Comment by ociule** [comment]
Fixing the broken plotly orca issue described above is possible by simply not passing a value for TEMP. This works just as well as passing the correct TEMP value from user_env.

However, many other env variables are missing, which breaks other software.

I also have a crash when importing openturns, which is traced to missing SYSTEMROOT, PATH, and possibly other env vars. Adding all user env vars to env fixes this, which is why I am strongly in favour of doing it.

The alternative is adding just enough env vars from user_env to fix the broken openturns, which is bound to require adding more later on to fix another broken package, and so on.

To add all user_env to env, the patch looks like this:
 * removing TEMP from win_env_keep in get_env

Then in start():
```python

        try:
            # Will load user variables, if the user profile is loaded
            user_env = win32profile.CreateEnvironmentBlock(token, False)
        except Exception as exc:
            self.log.warning("Failed to load user environment for %s: %s", self.user.name, exc)
        else:
            env.update(user_env)
            if not 'APPDATA' in user_env:
                #If the 'APPDATA' does not exist, the USERPROFILE points at the default
                #directory which is not writable. this changes the path over to public
                #documents, so at least its a writable location.
                user_env['USERPROFILE'] = user_env['PUBLIC']
```

I could delete the following block because it's done by `env.update(user_env)`:
```python
            if 'APPDATA' in user_env:
                env['APPDATA'] = user_env['APPDATA']
                env['USERPROFILE'] = user_env['USERPROFILE']
```

**Comment by ociule** [comment]
I submitter a PR solving this.

**Comment by adelcast** [comment]
@ociule thanks for fixing this! In general, jupyterhub restricts which variables are passed from the main process to the single servers, to avoid passing sensitive info (security tokens, etc). For cases were we use a token, I agree with you, makes sense to load all variables from the user profile. 

The only case were we need sane defaults is when there is no token. TEMP needs a value if there is no token (R kernel breaks if TEMP is not defined). Right now, as you detected, that default value is wrong. We should point instead to a temp folder accessible for all users.

**Comment by adelcast** [comment]
I added a commit to your change: 

https://github.com/ni/jupyterhub-winlocalprocessspawner/commit/a988e29b7aaae58bfaec9d66fe90abecedcdd9e2

If all single-user servers run with the same account (no auth token case), we do not want to expose the environment from the base account.

**Comment by ociule** [comment]
All right, fixed.
